### ISSUE TITLE
Duplicate IDs via API

### ISSUE THREAD

**Issue by craigmoyle** [mspnp/AzureNamingTool#114]
**Tool version**
V4.2.1

**Describe the bug**
We're trying to integrate the naming tool into our sub vending process and we're seeing it issue duplicate IDs for names generated during the process 

We're using Terraform and the Mastercard RestApi provider to manage the names as resources. We've tried rate limiting the provider to 1 per second but we're still seeing a handful of duplicates, even when increasing the App Service Plan resources. 

**To Reproduce**
Using the rest provider we ask for resource names for each subscription, resulting in up to 500 names being requested. 

Some of the names produced have the same ID making it impossible to manage via Terraform. 

**Expected behavior**
Each name produced by the API should have a unique ID

**Installation Method**
App Service - Windows

Terraform log with one ID produced for two names
![IMG-20241013-WA0004](https://github.com/user-attachments/assets/a7ca6c51-2170-42c4-9465-5d0eb6140c14)

ASP
![image](https://github.com/user-attachments/assets/e3e5bce2-29ec-411d-85b0-a79af4103c22)

Here is the provider configuration

```
provider "restapi" {
  alias                = "namingtool"
  uri                  = "https://app-mgt-prd-aue-01.azurewebsites.net"
  write_returns_object = true
  debug                = true
  rate_limit           = 1
  headers = {
    "APIKey"        = data.external.get_apikey.result.value
    "AdminPassword" = data.external.get_naming_tool_admin_pass.result.value
    "Authorization" = "Bearer ${data.external.get_naming_tool_access_token.result.accessToken}"
    "Content-Type"  = "application/json"
  }
}
```

Provider information
```
terraform {
  required_providers {
    restapi = {
      source                = "Mastercard/restapi"
      version               = "1.20.0"
      configuration_aliases = [restapi.namingtool]
    }
  }
}
```

and the module I'm using to call the naming tool

```
resource "restapi_object" "resource_name" {
  provider     = restapi.namingtool
  id_attribute = "resourceNameDetails/id"
  path         = "/api/ResourceNamingRequests/RequestName"
  read_path    = "/api/Admin/GetGeneratedName/{id}"
  destroy_path = "/api/Admin/DeleteGeneratedName/{id}"
  data = jsonencode({
    ResourceType        = var.ResourceType
    ResourceProjAppSvc  = var.ResourceProjAppSvc
    ResourceFunction    = var.ResourceFunction
    ResourceEnvironment = var.ResourceEnvironment
    ResourceLocation    = var.ResourceLocation
    ResourceInstance    = var.ResourceInstance
  })
}
```

and finally how I call the module

```
module "rg_name_aue_1" {
  source              = "../naming_tool"
  ResourceProjAppSvc  = var.workload
  ResourceEnvironment = var.environment
  ResourceInstance    = "01"
  ResourceLocation    = "aue"
  ResourceType        = "rg"
  ResourceFunction    = ""
  providers = {
    restapi.namingtool = restapi.namingtool
  }
}
```

**Comment by BryanSoltis** [comment]
Hi @craigmoyle,

The Azure Naming Tool uses JSON files for data storage to allow isolated deployments with no other resources required. Because of this, API calls should be throttled to ensure proper data updates/functionality. Excessive calls to the API can result in duplicated values.

I would recommend throttling your API calls even more to ensure the writes to the JSON files are complete before calling the API again. 

-Bryan

**Comment by craigmoyle** [comment]
Thanks for the update Bryan - unfortunately I can't throttle below 1 per second, at which rate still causes duplicates at the start of the run. 

Practically even if I could throttle further the amount of time required to complete the pipeline would be too long.

We ended up not deploying the tool - so this is just an FYI.

**Comment by craigmoyle** [comment]
Hi @BryanSoltis 

Just coming back to this as we have another customer looking to use the tool via the API. Wondering if a possible solution would be to use non sequential and more complex ids, this would reduce the chance of duplicate ids being issued at the same time and appears to be what the IPAM tool is doing

https://azure.github.io/ipam/#/api/README

Is this possible?

-Craig

**Comment by BryanSoltis** [comment]
Hi @craigmoyle,

There is a "Random" field type for a custom component. Currently, this allows you to generate a random value as part of the name generation process.

![Image](https://github.com/user-attachments/assets/8ff7f57c-a76d-4a28-8705-56bee8b26010)

![Image](https://github.com/user-attachments/assets/f13bb4ea-4f62-4f84-88c7-488e39616528)

The API does not auto-generate this value currently, I can look into updating the API so that if a Custom Component is "Random", it does not need to be specified when calling via the API and auto-generate the value.

I will let you know if I'm able to add this feature in the next version. 

-Bryan

**Comment by craigmoyle** [comment]
Thanks Bryan!
