### ISSUE TITLE
Add resource: IpGroup

### ISSUE THREAD

**Issue by Kadashnikov** [mspnp/AzureNamingTool#16]
**Is your feature request related to a problem? Please describe.**
IP group is missing so must be manually created. 

**Describe the solution you'd like**
"resource": Network/IpGroup
"ShortName": ipg or something similar

**Describe alternatives you've considered**
Only alternative is manual creation prone to human error naming. 

https://learn.microsoft.com/en-us/cli/azure/network/ip-group?view=azure-cli-latest

**Comment by BryanSoltis** [comment]
Hello @Kadashnikov,

Thank you for your feedback. The resource type definition is extremely manual and we are always lagging behind the many new Azure resources that are available (due to the complexity of defining the regex and verifying the approved short names, etc.). We will add this to our next resoucetypes.json file update.

- Bryan
