### ISSUE TITLE
Double delimiter when no optional component

### ISSUE THREAD

**Issue by koalajama** [mspnp/AzureNamingTool#39]
**Tool version**
3.1.1

**Describe the bug**
When not populating an optional component, two delimiters are present in the generated name instead of one.

**To Reproduce**
I have two custom components added to my name.
1. Parent Resource (Optional) - Open ended text
2. Resource Name - Open ended text

1. Go to Generate
2. Choose item and populate all fields, except optional.
3. Click Generate
4. See that output has two delimiters where the optional component would be, had it been populated.

**Expected behavior**
I would expect the system to recognize I did not populate the optional field, and only insert one delimiter.

**Screenshots**
![CustomComponent](https://github.com/mspnp/AzureNamingTool/assets/150177018/a642943f-2112-4664-906d-801c3d400442)
![GeneratedName](https://github.com/mspnp/AzureNamingTool/assets/150177018/8bd5746f-f1ea-40f7-8dfe-5051b134f61a)

**Installation Method**
FTP upload to Azure Web app

**Comment by BryanSoltis** [comment]
Hi @koalajama,

Thank you for your feedback. In looking at the screenshot, it seems as if your "Parent Resource" has a blank value (which I'm not sure how that is even possible. Because of that, the tool is interpreting the "blank" in the name as a valid value, therefore it is wrapping it with the delimiter. When entering a component option, a name/short is required, so I'm not sure how it allowed that as an option. 

If possible, can you export your "Parent Resource" config and provide it here?  Be sure to remove any sensitive information before posting.

Thank you!

-Bryan

**Comment by BryanSoltis** [comment]
CORRECTION - I see that the field is an "Open text" type, which explains the blank value. I will continue to research.

-Bryan

**Comment by BryanSoltis** [comment]
OK, I found the issue in the Generate page logic. This will be fixed in the next release.

- Bryan
