### ISSUE TITLE
Align with recommended abbreviations

### ISSUE THREAD

**Issue by benverhees** [mspnp/AzureNamingTool#42]
**Tool version**
v3.1.1

**Is your feature request related to a problem? Please describe.**
The abbreviations used by the tool do not match the [Recommended abbreviations for Azure resource types](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)

For example, `Microsoft.Web/serverFarms` is listed as [`asp`](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations#compute-and-web) in the recommendation, and in the AzureNamingTool it is configured as [`plan`](https://github.com/mspnp/AzureNamingTool/blob/eef10febee54d8c3e2124af662718ff5e71a4b18/src/repository/resourcetypes.json#L6221C17-L6221C17).

In this example, I think `plan` takes preference over `asp` seeing the unrelated resemblance with asp.net.

**Describe the solution you'd like**
It would be good if these resources would be aligned, so that we can refer to a human readable resource that matches the default configuration of the tool. In this case I would suggest updating the recommendation.

**Describe alternatives you've considered**
I have considered changing the configuration of the tool, but that would be overwritten when updating the configuration in the tool.

**Comment by jamasten** [comment]
@benverhees the engineers that manage the Azure Naming Tool do not belong to the CAF team. We have in the past worked together to align the short names / abbreviations, but the CAF team has made updates since then and not shared when they made the changes.  We plan to bring the tool in alignment, but the tool is passion project that we update in our spare time.  Feel free to submit PRs.
