### ISSUE TITLE
Document relation to Azure Cloud Adoption Framework naming convention

### ISSUE THREAD

**Issue by mloskot** [mspnp/AzureNamingTool#43]
**Tool version**

N/A

**Is your feature request related to a problem? Please describe.**

Microsoft CAF documentation contains reference to the Azure Naming Tool at 
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging

![image](https://github.com/mspnp/AzureNamingTool/assets/80741/df13ad7e-3d87-4812-80d1-c38ad195eba0)

But the Azure Naming Tool documentation does not seem to contain any reference or explanation how the tool relates to the conventions recommended by Microsoft. 

Moreover, it is missing reference to the Terraform and its Azure CAF provider, i.e. https://registry.terraform.io/providers/aztfmod/azurecaf/latest/docs, which is de-facto standard for naming Azure resources in any production-grade IaC.

**Describe the solution you'd like**

Update the Azure Naming Tool documentation explaining how it relates to the recommended best practices and the other tools.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by jamasten** [comment]
@mloskot we are not in control of the references in the CAF documentation. Please provide feedback on the learn page if you are unsatisfied with the references. Our tool was developed to replace the previous tool which was a spreadsheet that is still listed in the CAF documentation. I was unaware of the Terraform tooling and I wouldn't use it anyway since I don't write any code in Terraform.

The Azure Naming Tool allows resource naming through API calls which aligns with the behavior of the Azure Portal. Bicep, Terraform, PowerShell, etc. rely on API calls to Azure. The Azure Naming Tool is agnostic as well. Much of the data in the Azure Naming Tool aligns with the documentation that was available in 2021. We have worked with the CAF team to align resource short names, but we are separate teams, the Azure Naming Tool is a passion project, and maintained by engineers in their spare time.

Needless to say, we won't be adding references to other tools.  Where do you see a gap in the documentation for the Azure Naming Tool and how it relates to CAF? Have you deployed the tool? Have you reviewed the home page? The details are spelled out there and relates directly to the CAF documentation.
