### ISSUE TITLE
"Orgs" component excluded

### ISSUE THREAD

**Issue by lucafabbri365** [mspnp/AzureNamingTool#78]
**Tool version**
v4.0.0

**Describe the bug**
Why, in the default settings, has the _Orgs_ component been excluded for those resources whose names must be globally unique (_e.g. Storage Account_)? Wouldn't it be more correct to include it ?

**Comment by jamasten** [comment]
@lucafabbri365, the configuration is setup this way by default since most global names, like storage accounts and key vaults, have limited character lengths (24; 15 if domain join the storage account). Adding more components leads to names that are too long. There is flexibility in the tool to allow the Org component on any resource you desire. Feel free to update your installation with your desired configuration.

**Comment by lucafabbri365** [comment]
Hello @jamasten,
I was just wondering if it might be more correct to exclude _Units/Depts_ rather than Orgs; thinking that between the two, the former would increase the chances of unique names (for global resource names).

**Comment by jamasten** [comment]
@lucafabbri365, in v3.2.0 we added a random string component.  That would be the ideal component to use in this scenario.

**Comment by orhanmaden** [comment]
The only config I found was in `resourcecomponents.json`. It states Orgs component is enabled. 

```json
  {
    "id": 2,
    "name": "ResourceOrg",
    "displayName": "Orgs",
    "enabled": true,
    "sortOrder": 2,
    "isCustom": false,
    "isFreeText": false,
    "minLength": "1",
    "maxLength": "5",
    "enforceRandom": false,
    "alphanumeric": true,
    "applyDelimiterBefore": true,
    "applyDelimiterAfter": true,
    "description": ""
  },
```

It is also part of the components.

![Image](https://github.com/user-attachments/assets/6c1beafa-21df-4389-b94a-30400dce9b17)


It still doesn't show up.

![Image](https://github.com/user-attachments/assets/692ec475-1b88-4ea3-b921-0c89422314fb)

Why not?
